language: node_js

node_js:
  - "0.6"
  - "0.8"
  - "0.9"
  - "0.10"
  - "0.11"
  - "0.12"

script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
